### ISSUE TITLE
Ant Build Error

### ISSUE THREAD

**Issue by adityayuwono** [mindcandy/Teamcity-unity3d-build-runner-plugin#23]
I can't compile using Ant build although "Build>Rebuild Project" from Intellij Idea shows no error

here's the compile message
Created dir: V:\Teamcity-unity3d-build-runner-plugin\out\production\unityrunner-agent
javac
V:\Teamcity-unity3d-build-runner-plugin\unityrunner.xml:260: Compile failed; see the compiler error output for details.
    at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1180)
    at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:935)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.Main.start(Main.java:198)
    at org.apache.tools.ant.Main.main(Main.java:286)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:30)
V:\Teamcity-unity3d-build-runner-plugin\unityrunner.xml (260:46)'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
Compiling 21 source files to V:\Teamcity-unity3d-build-runner-plugin\out\production\unityrunner-agent
V:\Teamcity-unity3d-build-runner-plugin\agent\src\unityRunner\agent\UnityRunnerBuildServiceFactory.java:25: error: package org.apache.commons.configuration.plist does not exist
V:\Teamcity-unity3d-build-runner-plugin\agent\src\unityRunner\agent\UnityRunnerBuildServiceFactory.java (181:21)error: cannot find symbol class XMLPropertyListConfiguration
V:\Teamcity-unity3d-build-runner-plugin\agent\src\unityRunner\agent\UnityRunnerBuildServiceFactory.java (181:63)error: cannot find symbol class XMLPropertyListConfiguration
3 errors
V:\Teamcity-unity3d-build-runner-plugin\unityrunner.xml:260: Compile failed; see the compiler error output for details.
    at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1180)
    at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:935)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.Main.start(Main.java:198)
    at org.apache.tools.ant.Main.main(Main.java:286)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:30)
V:\Teamcity-unity3d-build-runner-plugin\unityrunner.xml:260: Compile failed; see the compiler error output for details.
    at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1180)
    at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:935)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.Main.start(Main.java:198)
    at org.apache.tools.ant.Main.main(Main.java:286)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:30)

**Comment by MitchellLawson-Burton** [comment]
Looks like the same issue I had in #19. I fixed it in #20.

You could check out my branch which is master + that fix: https://github.com/MitchellBurton/Teamcity-unity3d-build-runner-plugin/tree/Update-build

Or just do it manually:
In unityrunner.xml replace:
    `<pathelement location="${basedir}/lib/commons-configuration-1.9.jar"/>`
With:
    `<pathelement location="${basedir}/lib/commons-configuration-1.10.jar"/>`

Hope that helps.

**Comment by adityayuwono** [comment]
That helps, thanks
